[package]
name = "raytracer"
version = "0.1.0"
authors = ["Darcy Ryan <dryan@dgitsystems.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
float-cmp = "0.8.0"
smallvec = "1.5.1"

[dev-dependencies]
nom = "6"
